-- Function: round(DECFLOAT(34), DECFLOAT(34))

-- DROP FUNCTION round(DECFLOAT(34), DECFLOAT(34));

CREATE OR REPLACE FUNCTION round(
    DECFLOAT(34),
    DECFLOAT(34))
  RETURNS DECFLOAT(34)
$BODY$
 BEGIN
	RETURN ROUND($1, cast($2 as integer));
 END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION round(DECFLOAT(34), DECFLOAT(34))
  OWNER TO adempiere;
