-- Function: trunc(TIMESTAMP)

-- DROP FUNCTION trunc(TIMESTAMP);

CREATE OR REPLACE FUNCTION trunc(datetime TIMESTAMP)
  RETURNS TIMESTAMP AS
$BODY$
BEGIN
	RETURN CAST(datetime AS DATE);
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION trunc(TIMESTAMP)
  OWNER TO adempiere;
