-- View: m_movement_candidate_v

-- DROP VIEW m_movement_candidate_v;

 SELECT o.created,
    o.createdby,
    o.isactive,
    o.updated,
    o.updatedby,
    o.ad_client_id,
    o.ad_org_id,
    o.c_bpartner_id,
    o.dd_order_id,
    o.documentno,
    o.dateordered,
    o.c_doctype_id,
    o.poreference,
    o.description,
    o.salesrep_id,
    l.m_locator_id,
    l.m_locatorto_id
   FROM dd_order o
JOIN ddordln l ON o.dd_order_id = l.dd_order_id
  WHERE o.docstatus = 'CO' AND o.isdelivered = 'N' AND (o.c_doctype_id IN ( SELECT c_doctype.c_doctype_id
           FROM c_doctype
          WHERE c_doctype.docbasetype = 'DOO')) AND o.deliveryrule <> 'M' AND 
		  (l.m_product_id IS NULL OR (EXISTS ( SELECT p.m_product_id,
            p.ad_client_id,
            p.ad_org_id,
            p.isactive,
            p.created,
            p.createdby,
            p.updated,
            p.updatedby,
            p.value,
            p.name,
            p.description,
            p.documentnote,
            p.help,
            p.upc,
            p.sku,
            p.c_uom_id,
            p.salesrep_id,
            p.issummary,
            p.isstocked,
            p.ispurchased,
            p.issold,
            p.isbom,
            p.isinvoiceprintdetails,
            p.ispicklistprintdetails,
            p.isverified,
            p.c_revenuerecognition_id,
            p.m_product_category_id,
            p.classification,
            p.volume,
            p.weight,
            p.shelfwidth,
            p.shelfheight,
            p.shelfdepth,
            p.unitsperpallet,
            p.c_taxcategory_id,
            p.s_resource_id,
            p.discontinued,
            p.discontinuedby,
            p.processing,
            p.s_expensetype_id,
            p.producttype,
            p.imageurl,
            p.descriptionurl,
            p.guaranteedays,
            p.r_mailtext_id,
            p.versionno,
            p.m_attributeset_id,
            p.m_attributesetinstance_id,
            p.downloadurl,
            p.m_freightcategory_id,
            p.m_locator_id,
            p.guaranteedaysmin,
            p.iswebstorefeatured,
            p.isselfservice,
            p.c_subscriptiontype_id,
            p.isdropship,
            p.isexcludeautodelivery,
            p.group1,
            p.group2,
            p.istoformule,
            p.lowlevel,
            p.unitsperpack,
            p.discontinuedat,
            p.copyfrom,
            p.m_parttype_id,
            p.iskanban,
            p.ismanufactured,
            p.m_product_class_id,
            p.m_product_group_id,
            p.m_product_classification_id,
            p.isphantom
           FROM m_product p
          WHERE l.m_product_id = p.m_product_id AND p.isexcludeautodelivery = 'N'))) AND 
		  l.qtyordered <> l.qtydelivered AND l.confirmedqty > 0 AND o.isdropship = 'N' AND 
		  (l.m_product_id IS NOT NULL OR l.c_charge_id IS NOT NULL) AND 
		  NOT (EXISTS ( SELECT iol.m_movementline_id,
            iol.ad_client_id,
            iol.ad_org_id,
            iol.isactive,
            iol.created,
            iol.createdby,
            iol.updated,
            iol.updatedby,
            iol.m_movement_id,
            iol.m_locator_id,
            iol.m_locatorto_id,
            iol.m_product_id,
            iol.line,
            iol.movementqty,
            iol.description,
            iol.m_attributesetinstance_id,
            iol.confirmedqty,
            iol.scrappedqty,
            iol.targetqty,
            iol.processed,
            iol.m_attributesetinstanceto_id,
            iol.dd_orderline_id,
            iol.reversalline_id,
            io.m_movement_id,
            io.ad_client_id,
            io.ad_org_id,
            io.isactive,
            io.created,
            io.createdby,
            io.updatedby,
            io.updated,
            io.documentno,
            io.description,
            io.movementdate,
            io.posted,
            io.processed,
            io.processing,
            io.ad_orgtrx_id,
            io.c_project_id,
            io.c_campaign_id,
            io.c_activity_id,
            io.user1_id,
            io.user2_id,
            io.datereceived,
            io.docaction,
            io.docstatus,
            io.isintransit,
            io.c_doctype_id,
            io.isapproved,
            io.approvalamt,
            io.freightcostrule,
            io.m_shipper_id,
            io.priorityrule,
            io.salesrep_id,
            io.ad_user_id,
            io.c_bpartner_id,
            io.c_bpartner_location_id,
            io.c_charge_id,
            io.chargeamt,
            io.createfrom,
            io.dd_order_id,
            io.deliveryrule,
            io.deliveryviarule,
            io.freightamt,
            io.reversal_id,
            io.poreference,
            io.processedon
FROM mmovln iol
FROM mmovlncfm iol
FROM mmovlnma iol
             JOIN m_movement io ON iol.m_movement_id = io.m_movement_id
          WHERE iol.dd_orderline_id = l.dd_orderline_id AND (io.docstatus = ANY (ARRAY['IP', 'WC']))))
  GROUP BY o.created, o.createdby, o.isactive, o.updated, o.updatedby, o.ad_client_id, o.ad_org_id, 
  o.c_bpartner_id, o.dd_order_id, o.documentno, o.dateordered, o.c_doctype_id, o.poreference, o.description,
  o.salesrep_id, l.m_locator_id, l.m_locatorto_id;

