-- View: rv_hr_employeedependent

-- DROP VIEW rv_hr_employeedependent;

 SELECT e.ad_client_id,
    e.ad_org_id,
    e.isactive,
    e.created,
    e.createdby,
    e.updated,
    e.updatedby,
    e.value,
    e.taxid,
    e.name2,
    e.bpname,
    e.c_bpartner_id,
    e.c_bp_group_id,
    e.employeestatus,
    e.gender,
    e.birthday,
    e.maritalstatus,
    e.bloodgroup,
    e.placeofbirth_id,
    e.fathersname,
    e.marriageanniversarydate,
    e.paymentrule,
    e.hr_job_id,
    e.nationalcode,
    e.partnersname,
    e.identificationmark,
    e.ismanager,
    e.hr_employeetype_id,
    e.enddate,
    e.hr_department_id,
    e.sscode,
    e.hr_payroll_id,
    e.code,
    e.c_activity_id,
    e.startdate,
    e.hr_jobtype_id,
    e.hr_jobopening_id,
    e.hr_jobeducation_id,
    e.hr_careerlevel_id,
    e.hr_salaryrange_id,
    e.hr_salarystructure_id,
    e.hr_designation_id,
    e.hr_grade_id,
    e.c_project_id,
    e.ad_orgtrx_id,
    e.c_salesregion_id,
    e.hr_shiftgroup_id,
    e.hr_degree_id,
    e.c_campaign_id,
    e.hr_workgroup_id,
    e.monthlysalary,
    e.dailysalary,
    ed.hr_employeedependent_id,
    ed.birthday AS dependentbirthday,
    ed.hr_employee_id,
    ed.hr_relationship_id,
    ed.iscollectcash
JOIN hrempdpd ed ON ed.c_bpartner_id = e.c_bpartner_id AND ed.isactive = 'Y';

