-- View: rv_printformatdetail

-- DROP VIEW rv_printformatdetail;

 SELECT f.ad_client_id,
    f.ad_org_id,
    i.isactive,
    i.created,
    i.createdby,
    i.updated,
    i.updatedby,
    f.ad_printformat_id,
    f.name,
    f.description,
    f.istablebased,
    f.isform,
    f.ad_table_id,
    f.ad_reportview_id,
    f.ad_printpaper_id,
    f.ad_printcolor_id AS default_ad_printcolor_id,
    f.ad_printfont_id AS default_ad_printfont_id,
    f.isstandardheaderfooter,
    f.ad_printtableformat_id,
    f.headermargin,
    f.footermargin,
    f.printername,
    f.isdefault,
    i.ad_printformatitem_id,
    i.name AS itemname,
    i.printname,
    i.printnamesuffix,
    i.isprinted,
    i.printareatype,
    i.seqno,
    i.printformattype,
    i.ad_column_id,
    i.ad_printformatchild_id,
    i.imageisattached,
    i.imageurl,
    i.isrelativeposition,
    i.isnextline,
    i.xspace,
    i.yspace,
    i.xposition,
    i.yposition,
    i.maxwidth,
    i.isheightoneline,
    i.maxheight,
    i.isfixedwidth,
    i.issetnlposition,
    i.issuppressnull,
    i.belowcolumn,
    i.fieldalignmenttype,
    i.linealignmenttype,
    i.ad_printcolor_id,
    i.ad_printfont_id,
    i.isorderby,
    i.sortno,
    i.isgroupby,
    i.ispagebreak,
    i.isnextpage,
    i.issummarized,
    i.isaveraged,
    i.iscounted,
    i.ismincalc,
    i.ismaxcalc,
    i.isvariancecalc,
    i.isdeviationcalc,
    i.isrunningtotal,
    i.runningtotallines,
    i.ad_printgraph_id
FROM adprtfmt f
FROM adprtfi f
FROM adprtfit f
JOIN adprtfi i ON f.ad_printformat_id = i.ad_printformat_id;
JOIN adprtfit i ON f.ad_printformat_id = i.ad_printformat_id;

