-- View: rv_unposted

-- DROP VIEW rv_unposted;

 SELECT gl_journal.ad_client_id,
    gl_journal.ad_org_id,
    gl_journal.created,
    gl_journal.createdby,
    gl_journal.updated,
    gl_journal.updatedby,
    gl_journal.isactive,
    gl_journal.documentno,
    gl_journal.datedoc,
    gl_journal.dateacct,
    224 AS ad_table_id,
    gl_journal.gl_journal_id AS record_id,
    'N' AS issotrx,
    gl_journal.posted,
    gl_journal.processing,
    gl_journal.processed,
    gl_journal.docstatus,
    gl_journal.processedon,
    gl_journal.controlamt AS amount,
    NULL AS c_bpartner_id,
    gl_journal.c_doctype_id
  WHERE gl_journal.posted <> 'Y' AND gl_journal.docstatus <> 'VO'
UNION
 SELECT pi.ad_client_id,
    pi.ad_org_id,
    pi.created,
    pi.createdby,
    pi.updated,
    pi.updatedby,
    pi.isactive,
    (p.name || '_') || pi.line AS documentno,
    pi.movementdate AS datedoc,
    pi.movementdate AS dateacct,
    623 AS ad_table_id,
    pi.c_projectissue_id AS record_id,
    'N' AS issotrx,
    pi.posted,
    pi.processing,
    pi.processed,
    'CO' AS docstatus,
    pi.processedon,
    0.0 AS amount,
    p.c_bpartner_id,
    NULL AS c_doctype_id
FROM cprojiss pi
FROM cprjima pi
     JOIN c_project p ON pi.c_project_id = p.c_project_id
  WHERE pi.posted <> 'Y'
UNION
 SELECT c_invoice.ad_client_id,
    c_invoice.ad_org_id,
    c_invoice.created,
    c_invoice.createdby,
    c_invoice.updated,
    c_invoice.updatedby,
    c_invoice.isactive,
    c_invoice.documentno,
    c_invoice.dateinvoiced AS datedoc,
    c_invoice.dateacct,
    318 AS ad_table_id,
    c_invoice.c_invoice_id AS record_id,
    c_invoice.issotrx,
    c_invoice.posted,
    c_invoice.processing,
    c_invoice.processed,
    c_invoice.docstatus,
    c_invoice.processedon,
    c_invoice.grandtotal AS amount,
    c_invoice.c_bpartner_id,
    c_invoice.c_doctype_id
   FROM c_invoice
  WHERE c_invoice.posted <> 'Y' AND c_invoice.docstatus <> 'VO'
UNION
 SELECT m_inout.ad_client_id,
    m_inout.ad_org_id,
    m_inout.created,
    m_inout.createdby,
    m_inout.updated,
    m_inout.updatedby,
    m_inout.isactive,
    m_inout.documentno,
    m_inout.movementdate AS datedoc,
    m_inout.dateacct,
    319 AS ad_table_id,
    m_inout.m_inout_id AS record_id,
    m_inout.issotrx,
    m_inout.posted,
    m_inout.processing,
    m_inout.processed,
    m_inout.docstatus,
    m_inout.processedon,
    0.0 AS amount,
    m_inout.c_bpartner_id,
    m_inout.c_doctype_id
   FROM m_inout
  WHERE m_inout.posted <> 'Y' AND m_inout.docstatus <> 'VO'
UNION
 SELECT m_inventory.ad_client_id,
    m_inventory.ad_org_id,
    m_inventory.created,
    m_inventory.createdby,
    m_inventory.updated,
    m_inventory.updatedby,
    m_inventory.isactive,
    m_inventory.documentno,
    m_inventory.movementdate AS datedoc,
    m_inventory.movementdate AS dateacct,
    321 AS ad_table_id,
    m_inventory.m_inventory_id AS record_id,
    'N' AS issotrx,
    m_inventory.posted,
    m_inventory.processing,
    m_inventory.processed,
    m_inventory.docstatus,
    m_inventory.processedon,
    0.0 AS amount,
    NULL AS c_bpartner_id,
    m_inventory.c_doctype_id
  WHERE m_inventory.posted <> 'Y' AND m_inventory.docstatus <> 'VO'
UNION
 SELECT m_movement.ad_client_id,
    m_movement.ad_org_id,
    m_movement.created,
    m_movement.createdby,
    m_movement.updated,
    m_movement.updatedby,
    m_movement.isactive,
    m_movement.documentno,
    m_movement.movementdate AS datedoc,
    m_movement.movementdate AS dateacct,
    323 AS ad_table_id,
    m_movement.m_movement_id AS record_id,
    'N' AS issotrx,
    m_movement.posted,
    m_movement.processing,
    m_movement.processed,
    m_movement.docstatus,
    m_movement.processedon,
    0.0 AS amount,
    m_movement.c_bpartner_id,
    m_movement.c_doctype_id
  WHERE m_movement.posted <> 'Y' AND m_movement.docstatus <> 'VO'
UNION
 SELECT m_production.ad_client_id,
    m_production.ad_org_id,
    m_production.created,
    m_production.createdby,
    m_production.updated,
    m_production.updatedby,
    m_production.isactive,
    m_production.name AS documentno,
    m_production.movementdate AS datedoc,
    m_production.movementdate AS dateacct,
    325 AS ad_table_id,
    m_production.m_production_id AS record_id,
    'N' AS issotrx,
    m_production.posted,
    m_production.processing,
    m_production.processed,
    'CO' AS docstatus,
    m_production.processedon,
    0.0 AS amount,
    NULL AS c_bpartner_id,
    NULL AS c_doctype_id
  WHERE m_production.posted <> 'Y'
UNION
 SELECT c_cash.ad_client_id,
    c_cash.ad_org_id,
    c_cash.created,
    c_cash.createdby,
    c_cash.updated,
    c_cash.updatedby,
    c_cash.isactive,
    c_cash.name AS documentno,
    c_cash.statementdate AS datedoc,
    c_cash.dateacct,
    407 AS ad_table_id,
    c_cash.c_cash_id AS record_id,
    'N' AS issotrx,
    c_cash.posted,
    c_cash.processing,
    c_cash.processed,
    c_cash.docstatus,
    c_cash.processedon,
    c_cash.beginningbalance - c_cash.endingbalance AS amount,
    NULL AS c_bpartner_id,
    NULL AS c_doctype_id
   FROM c_cash
  WHERE c_cash.posted <> 'Y' AND c_cash.docstatus <> 'VO'
UNION
 SELECT c_payment.ad_client_id,
    c_payment.ad_org_id,
    c_payment.created,
    c_payment.createdby,
    c_payment.updated,
    c_payment.updatedby,
    c_payment.isactive,
    c_payment.documentno,
    c_payment.datetrx AS datedoc,
    c_payment.dateacct,
    335 AS ad_table_id,
    c_payment.c_payment_id AS record_id,
    'N' AS issotrx,
    c_payment.posted,
    c_payment.processing,
    c_payment.processed,
    c_payment.docstatus,
    c_payment.processedon,
    c_payment.payamt AS amount,
    c_payment.c_bpartner_id,
    c_payment.c_doctype_id
   FROM c_payment
  WHERE c_payment.posted <> 'Y' AND c_payment.docstatus <> 'VO'
UNION
 SELECT c_allocationhdr.ad_client_id,
    c_allocationhdr.ad_org_id,
    c_allocationhdr.created,
    c_allocationhdr.createdby,
    c_allocationhdr.updated,
    c_allocationhdr.updatedby,
    c_allocationhdr.isactive,
    c_allocationhdr.documentno,
    c_allocationhdr.datetrx AS datedoc,
    c_allocationhdr.dateacct,
    735 AS ad_table_id,
    c_allocationhdr.c_allocationhdr_id AS record_id,
    'N' AS issotrx,
    c_allocationhdr.posted,
    c_allocationhdr.processing,
    c_allocationhdr.processed,
    c_allocationhdr.docstatus,
    c_allocationhdr.processedon,
    c_allocationhdr.approvalamt AS amount,
    NULL AS c_bpartner_id,
    NULL AS c_doctype_id
  WHERE c_allocationhdr.posted <> 'Y' AND c_allocationhdr.docstatus <> 'VO'
UNION
 SELECT c_bankstatement.ad_client_id,
    c_bankstatement.ad_org_id,
    c_bankstatement.created,
    c_bankstatement.createdby,
    c_bankstatement.updated,
    c_bankstatement.updatedby,
    c_bankstatement.isactive,
    c_bankstatement.name AS documentno,
    c_bankstatement.statementdate AS datedoc,
    c_bankstatement.statementdate AS dateacct,
    392 AS ad_table_id,
    c_bankstatement.c_bankstatement_id AS record_id,
    'N' AS issotrx,
    c_bankstatement.posted,
    c_bankstatement.processing,
    c_bankstatement.processed,
    c_bankstatement.docstatus,
    c_bankstatement.processedon,
    c_bankstatement.beginningbalance - c_bankstatement.endingbalance AS amount,
    NULL AS c_bpartner_id,
    NULL AS c_doctype_id
  WHERE c_bankstatement.posted <> 'Y' AND c_bankstatement.docstatus <> 'VO'
UNION
 SELECT mi.ad_client_id,
    mi.ad_org_id,
    mi.created,
    mi.createdby,
    mi.updated,
    mi.updatedby,
    mi.isactive,
    mi.documentno,
    mi.datetrx AS datedoc,
    mi.dateacct,
    472 AS ad_table_id,
    mi.m_matchinv_id AS record_id,
    'N' AS issotrx,
    mi.posted,
    mi.processing,
    mi.processed,
    'CO' AS docstatus,
    mi.processedon,
    il.linetotalamt AS amount,
    i.c_bpartner_id,
    NULL AS c_doctype_id
   FROM m_matchinv mi
JOIN cinvln il ON mi.c_invoiceline_id = il.c_invoiceline_id
     LEFT JOIN c_invoice i ON il.c_invoice_id = i.c_invoice_id
  WHERE mi.posted <> 'Y'
UNION
 SELECT po.ad_client_id,
    po.ad_org_id,
    po.created,
    po.createdby,
    po.updated,
    po.updatedby,
    po.isactive,
    po.documentno,
    po.datetrx AS datedoc,
    po.dateacct,
    473 AS ad_table_id,
    po.m_matchpo_id AS record_id,
    'N' AS issotrx,
    po.posted,
    po.processing,
    po.processed,
    'CO' AS docstatus,
    po.processedon,
    0.0 AS amount,
    NULL AS c_bpartner_id,
    NULL AS c_doctype_id
   FROM m_matchpo po
JOIN cordln ol ON po.c_orderline_id = ol.c_orderline_id
     LEFT JOIN c_order o ON ol.c_order_id = o.c_order_id
  WHERE po.posted <> 'Y'
UNION
 SELECT c_order.ad_client_id,
    c_order.ad_org_id,
    c_order.created,
    c_order.createdby,
    c_order.updated,
    c_order.updatedby,
    c_order.isactive,
    c_order.documentno,
    c_order.dateordered AS datedoc,
    c_order.dateacct,
    259 AS ad_table_id,
    c_order.c_order_id AS record_id,
    c_order.issotrx,
    c_order.posted,
    c_order.processing,
    c_order.processed,
    c_order.docstatus,
    c_order.processedon,
    c_order.grandtotal AS amount,
    c_order.c_bpartner_id,
    c_order.c_doctype_id
   FROM c_order
  WHERE c_order.posted <> 'Y' AND c_order.docstatus <> 'VO'
UNION
 SELECT m_requisition.ad_client_id,
    m_requisition.ad_org_id,
    m_requisition.created,
    m_requisition.createdby,
    m_requisition.updated,
    m_requisition.updatedby,
    m_requisition.isactive,
    m_requisition.documentno,
    m_requisition.daterequired AS datedoc,
    m_requisition.daterequired AS dateacct,
    702 AS ad_table_id,
    m_requisition.m_requisition_id AS record_id,
    'N' AS issotrx,
    m_requisition.posted,
    m_requisition.processing,
    m_requisition.processed,
    m_requisition.docstatus,
    m_requisition.processedon,
    m_requisition.totallines AS amount,
    NULL AS c_bpartner_id,
    m_requisition.c_doctype_id
  WHERE m_requisition.posted <> 'Y' AND m_requisition.docstatus <> 'VO'
UNION
 SELECT hr_process.ad_client_id,
    hr_process.ad_org_id,
    hr_process.created,
    hr_process.createdby,
    hr_process.updated,
    hr_process.updatedby,
    hr_process.isactive,
    hr_process.documentno,
    hr_process.dateacct AS datedoc,
    hr_process.dateacct,
    53092 AS ad_table_id,
    hr_process.hr_process_id AS record_id,
    'N' AS issotrx,
    hr_process.posted,
    hr_process.processing,
    hr_process.processed,
    hr_process.docstatus::character(2) AS docstatus,
    hr_process.processedon,
    0.0 AS amount,
    hr_process.c_bpartner_id,
    hr_process.c_doctype_id
  WHERE hr_process.posted <> 'Y' AND hr_process.docstatus <> 'VO'
UNION
 SELECT a_asset_addition.ad_client_id,
    a_asset_addition.ad_org_id,
    a_asset_addition.created,
    a_asset_addition.createdby,
    a_asset_addition.updated,
    a_asset_addition.updatedby,
    a_asset_addition.isactive,
    a_asset_addition.documentno,
    a_asset_addition.dateacct AS datedoc,
    a_asset_addition.dateacct,
    53137 AS ad_table_id,
    a_asset_addition.a_asset_addition_id AS record_id,
    'N' AS issotrx,
    a_asset_addition.posted,
    a_asset_addition.processing,
    a_asset_addition.processed,
    a_asset_addition.docstatus::character(2) AS docstatus,
    a_asset_addition.processedon,
    a_asset_addition.assetvalueamt AS amount,
    ( SELECT i.c_bpartner_id
           FROM c_invoice i
          WHERE i.c_invoice_id = a_asset_addition.c_invoice_id) AS c_bpartner_id,
    a_asset_addition.c_doctype_id
  WHERE a_asset_addition.posted <> 'Y' AND a_asset_addition.docstatus <> 'VO'
UNION
 SELECT a_depreciation_entry.ad_client_id,
    a_depreciation_entry.ad_org_id,
    a_depreciation_entry.created,
    a_depreciation_entry.createdby,
    a_depreciation_entry.updated,
    a_depreciation_entry.updatedby,
    a_depreciation_entry.isactive,
    a_depreciation_entry.documentno,
    a_depreciation_entry.dateacct AS datedoc,
    a_depreciation_entry.dateacct,
    53121 AS ad_table_id,
    a_depreciation_entry.a_depreciation_entry_id AS record_id,
    'N' AS issotrx,
    a_depreciation_entry.posted,
    a_depreciation_entry.processing,
    a_depreciation_entry.processed,
    a_depreciation_entry.docstatus::character(2) AS docstatus,
    a_depreciation_entry.processedon,
    NULL AS amount,
    NULL AS c_bpartner_id,
    a_depreciation_entry.c_doctype_id
  WHERE a_depreciation_entry.posted <> 'Y' AND a_depreciation_entry.docstatus <> 'VO'
UNION
 SELECT a_asset_disposed.ad_client_id,
    a_asset_disposed.ad_org_id,
    a_asset_disposed.created,
    a_asset_disposed.createdby,
    a_asset_disposed.updated,
    a_asset_disposed.updatedby,
    a_asset_disposed.isactive,
    a_asset_disposed.documentno,
    a_asset_disposed.dateacct AS datedoc,
    a_asset_disposed.dateacct,
    53127 AS ad_table_id,
    a_asset_disposed.a_asset_disposed_id AS record_id,
    'N' AS issotrx,
    a_asset_disposed.posted,
    a_asset_disposed.processing,
    a_asset_disposed.processed,
    a_asset_disposed.docstatus::character(2) AS docstatus,
    a_asset_disposed.processedon,
    a_asset_disposed.a_disposal_amt AS amount,
    ( SELECT i.c_bpartner_id
           FROM c_invoice i
          WHERE i.c_invoice_id = a_asset_disposed.c_invoice_id) AS c_bpartner_id,
    a_asset_disposed.c_doctype_id
  WHERE a_asset_disposed.posted <> 'Y' AND a_asset_disposed.docstatus <> 'VO'
UNION
 SELECT pp_cost_collector.ad_client_id,
    pp_cost_collector.ad_org_id,
    pp_cost_collector.created,
    pp_cost_collector.createdby,
    pp_cost_collector.updated,
    pp_cost_collector.updatedby,
    pp_cost_collector.isactive,
    pp_cost_collector.documentno,
    pp_cost_collector.dateacct AS datedoc,
    pp_cost_collector.dateacct,
    53035 AS ad_table_id,
    pp_cost_collector.pp_cost_collector_id AS record_id,
    'N' AS issotrx,
    pp_cost_collector.posted,
    pp_cost_collector.processing,
    pp_cost_collector.processed,
    pp_cost_collector.docstatus,
    pp_cost_collector.processedon,
    NULL AS amount,
    NULL AS c_bpartner_id,
    pp_cost_collector.c_doctype_id
  WHERE pp_cost_collector.posted <> 'Y' AND pp_cost_collector.docstatus <> 'VO' AND pp_cost_collector.costcollectortype <> '160';

