-- View: rv_wm_inoutboundline

-- DROP VIEW rv_wm_inoutboundline;

 SELECT iob.ad_client_id,
    iob.ad_org_id,
    iob.created,
    iob.createdby,
    iob.isactive,
    iob.updated,
    iob.updatedby,
    iob.c_doctype_id,
    iob.dateprinted,
    iob.deliveryrule,
    iob.deliveryviarule,
    iob.docaction,
    iob.docstatus,
    iob.documentno,
    iob.dropship_bpartner_id,
    iob.dropship_location_id,
    iob.dropship_user_id,
    iob.freightamt,
    iob.freightcostrule,
    iob.m_freightcategory_id,
    iob.isapproved,
    iob.isdropship,
    iob.isintransit,
    iob.isprinted,
    iob.issotrx,
    iob.m_shipper_id,
    iob.m_warehouse_id,
    iob.poreference,
    iob.priorityrule,
    iob.salesrep_id,
    iob.trackingno,
    iob.volume,
    iob.weight,
    iobl.wm_inoutboundline_id,
    iobl.ad_orgtrx_id,
    iobl.c_activity_id,
    iobl.c_campaign_id,
    iobl.c_charge_id,
    iobl.c_orderline_id,
    iobl.c_projectphase_id,
    iobl.c_projecttask_id,
    iobl.c_project_id,
    iobl.c_uom_id,
    iobl.description,
    iobl.isdescription,
    iobl.line,
    iobl.m_attributesetinstance_id,
    iobl.wm_inoutbound_id,
    iobl.m_product_id,
    iobl.movementqty,
    iobl.pickedqty,
    iobl.processed,
    iobl.user1_id,
    iobl.user2_id,
    iobl.pickdate,
    iobl.shipdate,
    iobl.pp_mrp_id,
    iobl.dd_orderline_id,
    iobl.pp_order_bomline_id,
    iobl.dd_order_id,
    iobl.pp_order_id,
    iobl.c_order_id,
    ol.qtyordered,
    ol.qtydelivered,
    o.documentno AS referenceno,
    o.dateordered,
    o.datepromised,
    o.c_bpartner_id,
    bomqtyonhand(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyonhand,
    bomqtyreserved(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyreserved,
    bomqtyavailable(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyavailable
FROM wmiobndln iobl
FROM wmiobndlma iobl
JOIN wmiobnd iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndln iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndlma iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN cordln ol ON ol.c_orderline_id = iobl.c_orderline_id
     JOIN c_order o ON o.c_order_id = ol.c_order_id
     JOIN c_bpartner bp ON bp.c_bpartner_id = ol.c_bpartner_id
  WHERE NOT (EXISTS ( SELECT 1
          WHERE m_inoutline.c_orderline_id = iobl.c_orderline_id AND iobl.pickedqty >= 
		  m_inoutline.movementqty)) AND iob.issotrx = 'Y' AND iobl.processed = 'Y' AND 
		  ol.qtyordered <> ol.qtydelivered
UNION
 SELECT iob.ad_client_id,
    iob.ad_org_id,
    iob.created,
    iob.createdby,
    iob.isactive,
    iob.updated,
    iob.updatedby,
    iob.c_doctype_id,
    iob.dateprinted,
    iob.deliveryrule,
    iob.deliveryviarule,
    iob.docaction,
    iob.docstatus,
    iob.documentno,
    iob.dropship_bpartner_id,
    iob.dropship_location_id,
    iob.dropship_user_id,
    iob.freightamt,
    iob.freightcostrule,
    iob.m_freightcategory_id,
    iob.isapproved,
    iob.isdropship,
    iob.isintransit,
    iob.isprinted,
    iob.issotrx,
    iob.m_shipper_id,
    iob.m_warehouse_id,
    iob.poreference,
    iob.priorityrule,
    iob.salesrep_id,
    iob.trackingno,
    iob.volume,
    iob.weight,
    iobl.wm_inoutboundline_id,
    iobl.ad_orgtrx_id,
    iobl.c_activity_id,
    iobl.c_campaign_id,
    iobl.c_charge_id,
    iobl.c_orderline_id,
    iobl.c_projectphase_id,
    iobl.c_projecttask_id,
    iobl.c_project_id,
    iobl.c_uom_id,
    iobl.description,
    iobl.isdescription,
    iobl.line,
    iobl.m_attributesetinstance_id,
    iobl.wm_inoutbound_id,
    iobl.m_product_id,
    iobl.movementqty,
    iobl.pickedqty,
    iobl.processed,
    iobl.user1_id,
    iobl.user2_id,
    iobl.pickdate,
    iobl.shipdate,
    iobl.pp_mrp_id,
    iobl.dd_orderline_id,
    iobl.pp_order_bomline_id,
    iobl.dd_order_id,
    iobl.pp_order_id,
    iobl.c_order_id,
    ol.qtyordered,
    ol.qtydelivered,
    o.documentno AS referenceno,
    o.dateordered,
    o.datepromised,
    o.c_bpartner_id,
    bomqtyonhand(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyonhand,
    bomqtyreserved(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyreserved,
    bomqtyavailable(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyavailable
FROM wmiobndln iobl
FROM wmiobndlma iobl
JOIN wmiobnd iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndln iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndlma iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN ddordln ol ON ol.dd_orderline_id = iobl.dd_orderline_id
     JOIN dd_order o ON o.dd_order_id = ol.dd_order_id
     JOIN c_bpartner bp ON bp.c_bpartner_id = o.c_bpartner_id
  WHERE NOT (EXISTS ( SELECT 1
          WHERE m_movementline.dd_orderline_id = iobl.dd_orderline_id AND iobl.pickedqty >= 
		  m_movementline.movementqty)) AND iob.issotrx = 'Y' AND iobl.processed = 'Y' AND ol.qtyordered <> 
		  ol.qtydelivered
UNION
 SELECT iob.ad_client_id,
    iob.ad_org_id,
    iob.created,
    iob.createdby,
    iob.isactive,
    iob.updated,
    iob.updatedby,
    iob.c_doctype_id,
    iob.dateprinted,
    iob.deliveryrule,
    iob.deliveryviarule,
    iob.docaction,
    iob.docstatus,
    iob.documentno,
    iob.dropship_bpartner_id,
    iob.dropship_location_id,
    iob.dropship_user_id,
    iob.freightamt,
    iob.freightcostrule,
    iob.m_freightcategory_id,
    iob.isapproved,
    iob.isdropship,
    iob.isintransit,
    iob.isprinted,
    iob.issotrx,
    iob.m_shipper_id,
    iob.m_warehouse_id,
    iob.poreference,
    iob.priorityrule,
    iob.salesrep_id,
    iob.trackingno,
    iob.volume,
    iob.weight,
    iobl.wm_inoutboundline_id,
    iobl.ad_orgtrx_id,
    iobl.c_activity_id,
    iobl.c_campaign_id,
    iobl.c_charge_id,
    iobl.c_orderline_id,
    iobl.c_projectphase_id,
    iobl.c_projecttask_id,
    iobl.c_project_id,
    iobl.c_uom_id,
    iobl.description,
    iobl.isdescription,
    iobl.line,
    iobl.m_attributesetinstance_id,
    iobl.wm_inoutbound_id,
    iobl.m_product_id,
    iobl.movementqty,
    iobl.pickedqty,
    iobl.processed,
    iobl.user1_id,
    iobl.user2_id,
    iobl.pickdate,
    iobl.shipdate,
    iobl.pp_mrp_id,
    iobl.dd_orderline_id,
    iobl.pp_order_bomline_id,
    iobl.dd_order_id,
    iobl.pp_order_id,
    iobl.c_order_id,
    ol.qtyrequired AS qtyordered,
    ol.qtydelivered,
    o.documentno AS referenceno,
    o.dateordered,
    o.datepromised,
    bp.c_bpartner_id,
    bomqtyonhand(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyonhand,
    bomqtyreserved(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyreserved,
    bomqtyavailable(iobl.m_product_id, iob.m_warehouse_id, 0) AS qtyavailable
FROM wmiobndln iobl
FROM wmiobndlma iobl
JOIN wmiobnd iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndln iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN wmiobndlma iob ON iob.wm_inoutbound_id = iobl.wm_inoutbound_id
JOIN ppordboml ol ON ol.pp_order_bomline_id = iobl.pp_order_bomline_id
JOIN ppordbomlt ol ON ol.pp_order_bomline_id = iobl.pp_order_bomline_id
     JOIN pp_order o ON o.pp_order_id = ol.pp_order_id
     LEFT JOIN c_bpartner bp ON o.ad_org_id = bp.ad_orgbp_id
  WHERE NOT (EXISTS ( SELECT 1
FROM ppcstcol cc
FROM ppcstcolrm cc
          WHERE cc.pp_order_bomline_id = iobl.pp_order_bomline_id AND iobl.pickedqty >= 
		  cc.movementqty)) AND iob.issotrx = 'Y' AND iobl.processed = 'Y' AND ol.qtyrequired <> 
		  ol.qtydelivered;

